version: '3'
services:
  web:
    build: .
    volumes:
      - "/app"
    ports:
     - "8000:8000"
    links:
      - "redis"
      - "postgres"
    env_file:
      - ".env"
    command: "./docker-entrypoint.sh"
  redis:
    image: "redis"
  postgres:
    image: "postgres"
  celery:
    build: .
    command: celery -A dishmaker worker --loglevel=info -B
    volumes:
      - "/app"
    depends_on:
      - "redis"
    env_file:
      - ".env"
