# Generated by Django 2.1.5 on 2019-03-05 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190305_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='note',
        ),
    ]
