# Generated by Django 2.1.5 on 2019-03-05 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20190305_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteditem',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noteditem',
            name='note',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
