# Generated by Django 2.1.5 on 2019-02-12 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishmaker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dish',
            new_name='DishRecipe',
        ),
    ]
