# Generated by Django 2.1.5 on 2019-02-13 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishmaker', '0003_auto_20190213_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishRecipeIngredientProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishrecipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishmaker.DishRecipe')),
                ('ingredient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DishRecipeIngredientProxy', to='dishmaker.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='dishrecipe',
            name='members',
            field=models.ManyToManyField(through='dishmaker.DishRecipeIngredientProxy', to='dishmaker.Ingredient'),
        ),
    ]
