# Generated by Django 2.1.5 on 2019-02-13 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishmaker', '0004_auto_20190213_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishrecipe',
            old_name='members',
            new_name='ingredients',
        ),
    ]
