# Generated by Django 2.1.5 on 2019-02-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishmaker', '0009_auto_20190213_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishrecipe',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
