# Generated by Django 2.1.5 on 2019-02-13 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishmaker', '0010_auto_20190213_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishrecipeingredientproxy',
            name='dishrecipe_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dishrecipeingredientproxy',
            name='ingredient_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
