# Generated by Django 2.1.5 on 2019-02-13 03:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishmaker', '0011_auto_20190213_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientQuantityInDishProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RemoveField(
            model_name='dishrecipeingredientproxy',
            name='dishrecipe_id',
        ),
        migrations.RemoveField(
            model_name='dishrecipeingredientproxy',
            name='ingredient_id',
        ),
        migrations.AlterField(
            model_name='dishrecipe',
            name='ingredients',
            field=models.ManyToManyField(through='dishmaker.IngredientQuantityInDishProxy', to='dishmaker.Ingredient'),
        ),
        migrations.DeleteModel(
            name='DishRecipeIngredientProxy',
        ),
        migrations.AddField(
            model_name='ingredientquantityindishproxy',
            name='dishrecipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishmaker.DishRecipe'),
        ),
        migrations.AddField(
            model_name='ingredientquantityindishproxy',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IngredientQuantityInDishProxy', to='dishmaker.Ingredient'),
        ),
    ]
