# Generated by Django 2.1.5 on 2019-02-13 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishmaker', '0012_auto_20190213_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantityindishproxy',
            name='ingredient_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
