# Generated by Django 2.1.5 on 2019-02-13 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishmaker', '0013_auto_20190213_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantityindishproxy',
            name='dishrecipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishrecipe', to='dishmaker.DishRecipe'),
        ),
    ]
