# Generated by Django 2.1.5 on 2019-03-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishmaker', '0014_auto_20190213_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientquantityindishproxy',
            name='order_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='dishmaker.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='ingredients',
            field=models.ManyToManyField(through='dishmaker.IngredientQuantityInDishProxy', to='dishmaker.Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientquantityindishproxy',
            name='dishrecipe_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishrecipe', to='dishmaker.DishRecipe'),
        ),
        migrations.AlterField(
            model_name='ingredientquantityindishproxy',
            name='ingredient_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ing_dish_quan', to='dishmaker.Ingredient'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
