# Generated by Django 2.1.5 on 2019-03-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishmaker', '0015_auto_20190301_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
