# Generated by Django 2.1.5 on 2019-03-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishmaker', '0016_remove_order_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DishRecipe',
            new_name='Dish',
        ),
    ]
