# Generated by Django 2.1.5 on 2019-03-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishmaker', '0017_auto_20190301_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
