# Generated by Django 2.1.5 on 2019-03-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishmaker', '0020_ingredient_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
