# Generated by Django 2.1.5 on 2019-03-09 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishmaker', '0024_auto_20190309_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='author',
        ),
    ]
