# Generated by Django 2.1.5 on 2019-03-19 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishmaker', '0026_order_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dish_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dish', to='dishmaker.Dish'),
        ),
    ]
