# Generated by Django 2.1.5 on 2019-03-20 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_aizel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aizelclothitem',
            name='size',
        ),
        migrations.AddField(
            model_name='aizelclothitem',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='scrapy_aizel.Size'),
        ),
    ]
